# NumPy

### Используя средства библиотеки NumPy, без циклов, выполните следующие задания:

#### a) Создайте массив `arr_1` размером 3х4, все элементы которого равны 3.

#### b) Создайте массив `arr_2`, заполненный случайными целыми числами от 0 до 9, размером 2х4.

#### c) Выведите на экран количество элементов в созданных массивах `arr_1` и `arr_2`.

#### d) Соедините массивы `arr_1` и `arr_2` по нулевой оси.

#### e) Создайте массив `arr_3` из кортежа чисел `(1, 8, 6, 5, 8, 3)` с помощью функции `np.array()`.

#### f) Умножьте каждый элемент массива `arr_3` на число 3 и прибавьте к каждому элементу 1. Результат запишите в новый массив `arr_4`.

In [1]:
import numpy as np

In [ ]:
arr_1 = np.full((3, 4), 3)
print("a) arr_1:\n", arr_1)
print()

arr_2 = np.random.randint(0, 10, size=(2, 4))
print("b) arr_2:\n", arr_2)
print()

print("c) Количество элементов:")
print(f"arr_1: {arr_1.size} элементов")
print(f"arr_2: {arr_2.size} элементов")
print()

arr_combined = np.concatenate((arr_1, arr_2), axis=0)
print("d) Объединенный массив по оси 0:\n", arr_combined)
print()

arr_3 = np.array((1, 8, 6, 5, 8, 3))
print("e) arr_3:\n", arr_3)
print()

arr_4 = arr_3 * 3 + 1
print("f) arr_4:\n", arr_4)

a) arr_1:
 [[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]

b) arr_2:
 [[6 4 7 0]
 [1 2 0 1]]

c) Количество элементов:
arr_1: 12 элементов
arr_2: 8 элементов

d) Объединенный массив по оси 0:
 [[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [6 4 7 0]
 [1 2 0 1]]

e) arr_3:
 [1 8 6 5 8 3]

f) arr_4:
 [ 4 25 19 16 25 10]



#### g) Преобразуйте массив `arr_3` к двумерному массиву 2х3. Результат запишите в массив `arr_5`.

#### h) Определите минимальные элементы массива `arr_5` вдоль первой оси.

#### i) Вычислите среднее арифметическое всех элементов массива `arr_5`.

In [48]:
arr_5 = arr_3.reshape(2, 3)
print("g) arr_5 (2x3):\n", arr_5)
print()

print("h) Минимальные элементы вдоль оси 1:\n", np.min(arr_5, axis=1))
print()

print("i) Среднее арифметическое arr_5:", np.mean(arr_5))

g) arr_5 (2x3):
 [[1 8 6]
 [5 8 3]]

h) Минимальные элементы вдоль оси 1:
 [1 3]

i) Среднее арифметическое arr_5: 5.166666666666667


#### j) Создайте массив `arr_6`, состоящий из квадратов чисел от 0 до 10.

#### k) Выведите каждый второй элемент массива `arr_6`.

#### l) Выведите элементы массива `arr_6` в обратном порядке.

#### m) Каждому второму элементу массива `arr_6` присвойте значение 2.

#### n) Проверьте, есть ли в массиве `arr_6` значение 49.

#### o) Создайте двумерный массив `A`, состоящий из положительных и отрицательных чисел. Из массива `A` выберите все отрицательные элементы и запишите их в одномерный массив `B`.

In [ ]:
arr_6 = np.arange(11) ** 2
print("j) arr_6 (квадраты 0-10):\n", arr_6)
print()

print("k) Каждый второй элемент arr_6:\n", arr_6[1::2])
print()

print("l) arr_6 в обратном порядке:\n", arr_6[::-1])
print()

arr_6[1::2] = 2
print("m) arr_6 после замены каждого второго на 2:\n", arr_6)
print()

print("n) Есть ли значение 49 в arr_6:", 49 in arr_6)
print()

A = np.array([[1, -2, 3], 
              [-4, 5, -6], 
              [7, -8, 9]])
B = A[A < 0]
print("o) Массив A:\n", A)
print("Отрицательные элементы массива А):\n", B)

j) arr_6 (квадраты 0-10):
 [  0   1   4   9  16  25  36  49  64  81 100]

k) Каждый второй элемент arr_6:
 [ 1  9 25 49 81]

l) arr_6 в обратном порядке:
 [100  81  64  49  36  25  16   9   4   1   0]

m) arr_6 после замены каждого второго на 2:
 [  0   2   4   2  16   2  36   2  64   2 100]

n) Есть ли значение 49 в arr_6: False

o) Массив A:
 [[ 1 -2  3]
 [-4  5 -6]
 [ 7 -8  9]]
Отрицательные элементы массива А):
 [-2 -4 -6 -8]


### Напишите программы, которые создают следующие массивы NumPy:
#### 1. Массив со значениями 1, 7, 13, 105. Посчитайте и выведите на экран размер памяти, который он занимает. Сохраните массив в текстовый и бинарный файлы. Затем загрузите его и выведите на экран.

In [4]:
arr = np.array([1, 7, 13, 105])
print("1. Массив:", arr)

print(f"Размер памяти: {arr.nbytes} байт")

np.savetxt('array.txt', arr)
print("Массив сохранен в array.txt")

np.save('array.npy', arr)
print("Массив сохранен в array.npy")

loaded_from_txt = np.loadtxt('array.txt').astype(int)
print("Загружен из текстового файла:", loaded_from_txt)

loaded_from_binary = np.load('array.npy')
print("Загружен из бинарного файла:", loaded_from_binary)

1. Массив: [  1   7  13 105]
Размер памяти: 32 байт
Массив сохранен в array.txt
Массив сохранен в array.npy
Загружен из текстового файла: [  1   7  13 105]
Загружен из бинарного файла: [  1   7  13 105]


#### 2. Три массива: из 10 нулей, 10 единиц, 10 пятерок.

#### 3. Массив последовательности четных целых чисел от 30 до 70.

#### 4. Массив из 10 элементов со значениями, равномерно распределенными между 5 и 50.

#### 5. Массив 3x3x3 из 27 случайных чисел в диапазоне от 1 до 100.

#### 6. Массив 3х4, заполненной значениями от 30 до 41.

In [6]:
print("2. Массивы из нулей, единиц и пятерок:")
zeros_arr = np.zeros(10)
ones_arr = np.ones(10)
fives_arr = np.full(10, 5)
print("Нули:", zeros_arr)
print("Единицы:", ones_arr)
print("Пятерки:", fives_arr)
print()

print("3. Массив четных чисел от 30 до 70:")
even_arr = np.arange(30, 71, 2)
print(even_arr)
print()

print("4. Массив из 10 элементов, равномерно распределенных между 5 и 50:")
uniform_arr = np.linspace(5, 50, 10).astype(int)
print(uniform_arr)
print()

print("5. Массив 3x3x3 из случайных чисел от 1 до 100:")
random_arr = np.random.randint(1, 101, size=(3, 3, 3))
print(random_arr)
print()

print("6. Массив 3x4, заполненный значениями от 30 до 41:")
range_arr = np.arange(30, 42).reshape(3, 4)
print(range_arr)

2. Массивы из нулей, единиц и пятерок:
Нули: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Единицы: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Пятерки: [5 5 5 5 5 5 5 5 5 5]

3. Массив четных чисел от 30 до 70:
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]

4. Массив из 10 элементов, равномерно распределенных между 5 и 50:
[ 5 10 15 20 25 30 35 40 45 50]

5. Массив 3x3x3 из случайных чисел от 1 до 100:
[[[ 1 63 90]
  [22 32 53]
  [19 47 53]]

 [[25 88 38]
  [ 7 21 64]
  [27 20 39]]

 [[ 1 83  7]
  [56 49 42]
  [40 34 85]]]

6. Массив 3x4, заполненный значениями от 30 до 41:
[[30 31 32 33]
 [34 35 36 37]
 [38 39 40 41]]


#### 7. Массив 10x10, в котором элементы на границах равны 1, а внутри 0.

#### 8. Массив 5x5 из нулей с элементами на главной диагонали равными 1, 2, 3, 4, 5.

#### 9. Массив 4x4, в котором 0 и 1 расположены в шахматном порядке, с нулями на главной диагонали.

#### 10. Массив, заполненный всеми днями марта 2017 года. Тип данных массива – дата.

In [5]:
print("7. Массив 10x10 с границами 1 и внутренней частью 0:")
border_arr = np.ones((10, 10))
border_arr[1:-1, 1:-1] = 0
print(border_arr.astype(int))
print()

print("8. Массив 5x5 из нулей с элементами на главной диагонали 1, 2, 3, 4, 5:")
diag_arr = np.diag([1, 2, 3, 4, 5])
print(diag_arr)
print()

print("9. Массив 4x4 в шахматном порядке с нулями на главной диагонали:")
chess = np.zeros((4, 4), dtype=int)
chess[::2, 1::2] = 1
chess[1::2, ::2] = 1
print(chess)
print()

print("10. Массив всех дней марта 2017 года:")
march_2017 = np.arange('2017-03-01', '2017-04-01', dtype='datetime64')
print(march_2017)

7. Массив 10x10 с границами 1 и внутренней частью 0:
[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]

8. Массив 5x5 из нулей с элементами на главной диагонали 1, 2, 3, 4, 5:
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]

9. Массив 4x4 в шахматном порядке с нулями на главной диагонали:
[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]

10. Массив всех дней марта 2017 года:
['2017-03-01' '2017-03-02' '2017-03-03' '2017-03-04' '2017-03-05'
 '2017-03-06' '2017-03-07' '2017-03-08' '2017-03-09' '2017-03-10'
 '2017-03-11' '2017-03-12' '2017-03-13' '2017-03-14' '2017-03-15'
 '2017-03-16' '2017-03-17' '2017-03-18' '2017-03-19' '2017-03-20'
 '2017-03-21' '2017-03-22' '2017-03-23' '2017-03-24' '2017-03-25'
 '2017-03-26' '2017-03-27' '2017-03-28' '2017-03-29' '2017-03-30'
 '2017-03-31']


#### Создайте две numpy матрицы размера nхn и заполните их случайными значениями.
#### Посчитайте их поэлементное и матричное произведения. Для этого реализуйте функции:
1. mult – матричное перемножение без использования numpy
2. el_mult – поэлементное перемножение без использования numpy
3. np_mult – матричное перемножение c использованием numpy
4. np_el_mult – поэлементное перемножение с использованием numpy
##### При помощи timeit засеките время работы функций для n = 100000 (для чистоты эксперимента засекайте время на одинаковых матрицах).
#### *Во сколько раз numpy версия функций работает быстрее реализаций без numpy?*

In [ ]:
import random
import timeit

def mult(A, B):
    n = len(A)
    C = [[0] * n for _ in range(n)]
    for i in range(n):
        for j in range(n):
            for k in range(n):
                C[i][j] += A[i][k] * B[k][j]
    return C

def el_mult(A, B):
    n = len(A)
    C = [[0] * n for _ in range(n)]
    for i in range(n):
        for j in range(n):
            C[i][j] = A[i][j] * B[i][j]
    return C

def np_mult(A, B):
    return np.dot(A, B)

def np_el_mult(A, B):
    return A * B

n = 1000
A = [[random.random() for _ in range(n)] for _ in range(n)]
B = [[random.random() for _ in range(n)] for _ in range(n)]

A_np = np.array(A)
B_np = np.array(B)

t_python_mult = timeit.timeit(lambda: mult(A, B), number=1)
t_python_el = timeit.timeit(lambda: el_mult(A, B), number=1)
t_numpy_mult = timeit.timeit(lambda: np_mult(A_np, B_np), number=1)
t_numpy_el = timeit.timeit(lambda: np_el_mult(A_np, B_np), number=1)


print(f"Матричное без Numpy: {t_python_mult}")
print(f"Матричное с Numpy: {t_numpy_mult}")
print(f"С NumPy быстрее в {t_python_mult / t_numpy_mult} раз\n")

print(f"Поэлементное без Numpy: {t_python_el}")
print(f"Поэлементное с Numpy: {t_numpy_el}")
print(f"С NumPy быстрее в {t_python_el / t_numpy_el} раз")

Матричное без Numpy: 92.1203239000024
Матричное с Numpy: 0.016482200000609737
С NumPy быстрее в 5589.079364198623 раз

Поэлементное без Numpy: 0.06776030000037281
Поэлементное с Numpy: 0.0029638999985763803
С NumPy быстрее в 22.861871194345092 раз


# Результаты для n = 1000
### На 100000 комп не вывозит

![result](https://raw.githubusercontent.com/Rumuantsev/ML-sem2/refs/heads/master/lab1/Numpy/resunlts.jpg)



### Создайте и заполните случайными значениями матрицы A, B, C и D (размерности смотрите в формуле). Вычислите следующее выражение:

![image1](https://raw.githubusercontent.com/Rumuantsev/ML-sem2/refs/heads/master/lab1/Numpy/image1.jpg)

In [1]:
n, m = 4, 3  # можно поменять

A = np.random.randint(1, 10, size=(n, m)) 
B = np.random.randint(1, 10, size=(m, 1))
C = np.random.randint(1, 10, size=(m, n))
D = np.random.randint(1, 10, size=(m, 1))

AB = A.dot(B)         
CTD = C.T.dot(D)    

result = 5 * AB + CTD

print("A:\n", A)
print("B:\n", B)
print("C:\n", C)
print("D:\n", D)
print("\nРезультат:\n", result)

NameError: name 'np' is not defined

![image2](https://raw.githubusercontent.com/Rumuantsev/ML-sem2-lab1/refs/heads/master/Numpy/image2.jpg)

In [ ]:
X = np.array([[-3, 4, 1],
              [4, 3, 1]])

y = np.array([[10],
              [12]])

lambda_val = 0.1
I_n = np.eye(3)  

X_T = X.T  
X_T_X = X_T.dot(X)  
lambda_I = lambda_val * I_n 
matrix_sum = X_T_X + lambda_I  
matrix_inv = np.linalg.inv(matrix_sum)  
X_T_y = X_T.dot(y)  

result = matrix_inv.dot(X_T_y)  

print("\nРезультат:\n", result)


Результат:
 [[0.68478852]
 [2.80148778]
 [0.81180812]]
