![image.png](1.jpg)

Можно увидеть, что зависимость между x и y выражается как y = −x. То есть оптимальные 
значения весов сети будет w1 = −1, w0 = 0.  
Напишите программу для обнаружения этих значений при помощи алгоритма 
классического ГС. Для этого вам потребуется составить функцию потерь L(w). Частные 
производные можете посчитать аналитически и использовать в программе. Для старта 
спуска возьмем a0 = (0,0), h = 0.1, причем мы предполагаем, что первая координата позиции 
"шарика" соответствует весу w0, а вторая координата соответствует весу w1. 
Сколько итераций потребовалось, чтобы достигнуть точки минимума?

In [ ]:
import math

xs = [-1, 0, 1]
ys = [ 1, 0,-1]

h = 0.1           
w0 = 0.0         
w1 = 0.0        
tol = 1e-6    
max_iter = 10000

def loss(w0,w1):
    return sum((w1*x + w0 - y)**2 for x,y in zip(xs,ys))

def grad(w0,w1):
    d_w0 = 6.0 * w0
    d_w1 = 4.0 * (w1 + 1.0)
    return d_w0, d_w1

target = (0.0, -1.0)
def dist(w0,w1):
    return math.hypot(w0 - target[0], w1 - target[1])

it = 0
while dist(w0,w1) > tol and it < max_iter:
    d0, d1 = grad(w0,w1)
    w0 -= h * d0
    w1 -= h * d1
    it += 1

print("Итераций:", it)
print("w0 =", w0, "w1 =", w1)
print("Loss =", loss(w0,w1))


Итераций: 28
w0 = 0.0 w1 = -0.9999993859057786
Loss = 7.542234254224322e-13


![image.png](2.jpg)

Можно увидеть, что зависимость между x и y выражается как y = x + 1. То есть оптимальные 
значения весов сети будет w1 = 1, w0 = 1.  
Используйте программу из предыдущего задания для обнаружения этих значений при 
помощи алгоритма классического ГС. Для этого вам потребуется составить функцию 
потерь L(w). Частные производные можете посчитать аналитически и использовать в 
программе. Для старта спуска возьмем a0 = (0,0), h = 0.1, причем мы предполагаем, что 
первая координата позиции "шарика" соответствует весу w0, а вторая координата 
соответствует весу w1. 
Сколько итераций потребовалось, чтобы достигнуть точки минимума?

In [10]:
import math

xs = [0,1,2]
ys = [1,2,3]

h = 0.1          
w0 = 0.0          
w1 = 0.0          
tol = 1e-6        
max_iter = 10000

def loss(w0,w1):
    return sum((w1*x + w0 - y)**2 for x,y in zip(xs,ys))

def grad(w0,w1):
    d_w0 = 6.0 * (w0 + w1 - 2.0)
    d_w1 = 10.0 * w1 + 6.0 * w0 - 16.0
    return d_w0, d_w1

target = (1.0, 1.0)
def dist(w0,w1):
    return math.hypot(w0 - target[0], w1 - target[1])

it = 0
while dist(w0,w1) > tol and it < max_iter:
    d0, d1 = grad(w0,w1)
    w0 -= h * d0
    w1 -= h * d1
    it += 1

print("Итераций:", it)
print("w0 =", w0, "w1 =", w1)
print("Loss =", loss(w0,w1))


Итераций: 68
w0 = 0.9999992939574602 w1 = 1.0000005088866706
Loss = 6.345425971139755e-13


Теперь измените программу из задания №2 и замените классический ГС на стохастический. 
Так как в ТВ у нас 3 объекта, то на каждой эпохе у вас будет три итерации. При этом за 
одну эпоху должны быть использованы все объекты, но в случайном порядке. 
Сколько итераций потребовалось, чтобы достигнуть точки минимума?

In [ ]:
import random, math

xs = [0,1,2]
ys = [1,2,3]
h = 0.1
tol = 1e-6
max_iters = 100000

w0, w1 = 0.0, 0.0
it = 0
rnd = random.Random(42)   

def dist2(w0, w1, target=(1.0,1.0)):
    dx = w0 - target[0]
    dy = w1 - target[1]
    return math.sqrt(dx*dx + dy*dy)

while dist2(w0, w1) > tol and it < max_iters:
    idxs = [0,1,2]
    rnd.shuffle(idxs)          
    for i in idxs:
        x, y = xs[i], ys[i]
        e = (w1*x + w0 - y)
        d0 = 2*e
        d1 = 2*e*x
        w0 -= h * d0
        w1 -= h * d1
        it += 1
        if dist2(w0, w1) <= tol:
            break

print("Итераций:", it)
print("Эпох (прибл.):", it/3.0)
print("w0, w1:", w0, w1)


Итераций: 185
Эпох (прибл.): 61.666666666666664
w0, w1: 0.9999992421337919 1.0000006315551735


Теперь измените программу из задания №1 и замените классический ГС на стохастический 
по мини-батчам. Размер батча равен 2. Так как в ТВ у нас 3 объекта, то на каждой эпохе у 
вас будет две итерации. При этом батчи у вас будут пересекаться. Например, в первом батче 
будут 1 и 2 объекты, а во втором батче – 2 и 3 объекты. Главное, чтобы за одну эпоху были 
использованы все объекты. 
Сколько итераций потребовалось, чтобы достигнуть точки минимума? 

In [ ]:
import math

xs = [-1, 0, 1]
ys = [ 1,  0,-1]

h = 0.1
w0 = 0.0
w1 = 0.0
tol = 1e-6
max_iters = 100000

batches = [(0,1), (1,2)]

def grad_single(x, y, w0, w1):
    e = (w1 * x + w0 - y)
    return 2*e, 2*e*x

def close_enough(w0, w1, target=(0.0, -1.0), tol=1e-6):
    dx = w0 - target[0]
    dy = w1 - target[1]
    return dx*dx + dy*dy <= tol*tol

it = 0
while not close_enough(w0, w1) and it < max_iters:
    for batch in batches:

        d0_sum = 0.0
        d1_sum = 0.0
        for i in batch:
            d0_i, d1_i = grad_single(xs[i], ys[i], w0, w1)
            d0_sum += d0_i
            d1_sum += d1_i

        k = len(batch)
        d0_avg = d0_sum / k
        d1_avg = d1_sum / k

        w0 -= h * d0_avg
        w1 -= h * d1_avg

        it += 1
        if close_enough(w0, w1):
            break

print("Итераций (батч-апдейты):", it)
print("w0, w1:", w0, w1)
print("Loss:", sum((w1*x + w0 - y)**2 for x,y in zip(xs,ys)))


Итераций (батч-апдейты): 124
w0, w1: -5.549853859608136e-08 -0.999999059800455
Loss: 1.777190632170155e-12


![image.png](5.png)

Запишите эти данные в вашей программе (способ хранения выберите самостоятельно) и выполните следующие задания:

1. Реализуйте функцию нормализации по формуле $x_i = \frac{x_i - a}{b - a}$, где $a$ и $b$ – соответственно минимальное и максимальное значения в столбце.
   
   Выведите всю таблицу с нормализованными значениями нецелевых признаков на экран.
   
   Проведите нормализацию нового объекта А с помощью параметров, которые были вычислены по тренировочной выборке. Выведите результат на экран.

2. Реализуйте функцию нормализации по формуле $x_i = \frac{x_i - x_s}{s}$, где $x_s$ – среднее значение столбца, $s$ – величина отклонения в столбце.
   
   Выведите всю таблицу с нормализованными значениями нецелевых признаков на экран.
   
   Проведите нормализацию нового объекта А с помощью параметров, которые были вычислены по тренировочной выборке. Выведите результат на экран.

In [26]:
import numpy as np

data = np.array([[50,0,1],[60,1,2],[80,1,3],[100,0,4]], float)
A = np.array([90,1,1], float)

a, b = data.min(axis=0), data.max(axis=0)
norm = (data - a) / (b - a)
A_norm = (A - a) / (b - a)

print("Входные данные:\n", data)
print("\nПервый вид нормализации:\n", norm)
print("\nНовый объект A:\n", A_norm)

mean = data.mean(axis=0)
std = data.std(axis=0)
norm = (data - mean) / std
A_norm = (A - mean) / std

print("\nВторой вид нормализации:\n", norm)
print("\nНовый объект A:\n", A_norm)


Входные данные:
 [[ 50.   0.   1.]
 [ 60.   1.   2.]
 [ 80.   1.   3.]
 [100.   0.   4.]]

Первый вид нормализации:
 [[0.         0.         0.        ]
 [0.2        1.         0.33333333]
 [0.6        1.         0.66666667]
 [1.         0.         1.        ]]

Новый объект A:
 [0.8 1.  0. ]

Второй вид нормализации:
 [[-1.1717002  -1.         -1.34164079]
 [-0.65094455  1.         -0.4472136 ]
 [ 0.39056673  1.          0.4472136 ]
 [ 1.43207802 -1.          1.34164079]]

Новый объект A:
 [ 0.91132238  1.         -1.34164079]
